library(robotstxt)
path<-paths_allowed("https://www.foxsports.com/soccer/fifa-world-cup/history")
library(rvest)
link<-"https://www.foxsports.com/soccer/fifa-world-cup/history"
web<-read_html(link)
library(dplyr)
host<-web%>%html_nodes("tr > :nth-child(2)")%>%html_text()
View(host)
year<-web%>%html_nodes(".wisbb_year span , th:nth-child(1)")%>%html_text()
View(year)
champion<-web%>%html_nodes("td:nth-child(3) span , th:nth-child(3)")%>%html_text()
View(champion)
runnerup<-web%>%html_nodes(".wisbb_heManager:nth-child(4)")%>%html_text()
View(runnerup)
WC_history<-data.frame(host,year,champion,runnerup)
write.csv(WC_history,"WC-history.csv")
